import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Activity } from 'lucide-react';
import { fetchPortfolioHealth } from '../../api';

export default function PortfolioPulseTile() {
    const [health, setHealth] = useState({
        healthScore: 0,
        changeVsLastMonth: '+0.0',
        loanCount: 0
    });

    useEffect(() => {
        const loadHealth = async () => {
            const res = await fetchPortfolioHealth();
            setHealth(res.data || { healthScore: 0, changeVsLastMonth: '+0.0', loanCount: 0 });
        };
        loadHealth();
    }, []);

    return (
        <div className="col-span-1 md:col-span-3 h-64 relative rounded-3xl overflow-hidden border border-white/10 group">
            {/* Animated Liquid Background */}
            <div className="absolute inset-0 bg-gradient-to-br from-[#1e293b] to-[#0f172a]" />
            <div className="absolute inset-0 opacity-30">
                <div className="absolute top-0 left-0 w-[200%] h-[200%] bg-gradient-to-r from-transparent via-blue-500/20 to-transparent transform rotate-45 animate-[pulse_15s_ease-in-out_infinite]" />
                <div className="absolute bottom-0 right-0 w-[200%] h-[200%] bg-gradient-to-l from-transparent via-green-500/10 to-transparent transform -rotate-45 animate-[pulse_20s_ease-in-out_infinite]" />
            </div>

            {/* Content Layer */}
            <div className="absolute inset-0 p-8 flex flex-col justify-between z-10 backdrop-blur-[2px]">
                <div className="flex justify-between items-start">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                            <div className="p-2 rounded-lg bg-white/5 border border-white/10">
                                <Activity className="text-secondary" size={20} />
                            </div>
                            <h3 className="text-lg font-medium text-gray-300">Portfolio Health Pulse</h3>
                        </div>
                        <p className="text-sm text-gray-500 max-w-md">
                            Real-time liquidity analysis and stability metrics generated by Greener AI Neural Core.
                            {health.loanCount > 0 && ` Based on ${health.loanCount} active loans.`}
                        </p>
                    </div>

                    <div className="text-right">
                        <div className="text-5xl font-bold text-white tracking-tight">
                            {parseFloat(health.healthScore).toFixed(1)}<span className="text-2xl text-secondary">%</span>
                        </div>
                        <div className={`text-sm font-medium ${health.changeVsLastMonth.startsWith('+') ? 'text-green-400' : 'text-red-400'}`}>
                            {health.changeVsLastMonth}% vs last month
                        </div>
                    </div>
                </div>

                {/* Liquid Gauge */}
                <div className="relative h-16 w-full bg-white/5 rounded-full overflow-hidden border border-white/5">
                    <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${health.healthScore}%` }}
                        transition={{ duration: 1.5, ease: "circOut", delay: 0.5 }}
                        className="h-full bg-gradient-to-r from-blue-600 via-cyan-500 to-green-500 relative"
                    >
                        {/* Shimmer on bar */}
                        <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent w-full h-full animate-[shimmer_2s_infinite]" />
                    </motion.div>
                </div>
            </div>

            {/* Parallax Dust */}
            <div className="absolute inset-0 pointer-events-none mix-blend-screen opacity-50 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] bg-opacity-20" />
        </div>
    );
}
